# Generated by Django 2.2 on 2019-05-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190530_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('movieid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('length', models.CharField(max_length=10)),
                ('genres', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('poster', models.URLField(default='')),
                ('plot', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GenresPopularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='movie.Genre')),
                ('movieid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
