# Generated by Django 2.2 on 2019-05-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_genre_genrespopularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='length',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='year',
        ),
        migrations.RemoveField(
            model_name='genrespopularity',
            name='movieid',
        ),
        migrations.AddField(
            model_name='genrespopularity',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popularity',
            name='genres',
            field=models.IntegerField(default=0),
        ),
    ]
